export const AUTH_TYPES = {
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_ERROR: 'LOGIN_ERROR',
   REGISTER_SUCCESS: 'REGISTER_SUCCESS',
   REGISTER_ERROR: 'REGISTER_ERROR',
   SIGNOUT: 'SIGNOUT',
   LOADING: 'LOADING',
   CHECK_ROLE: 'CHECK_ROLE'
}


export const ADMIN_TYPES = {
   GET_ALL_SERVICES: 'GET_ALL_SERVICES',
   SERVICE_TO_EDIT:'SERVICE_TO_EDIT',
   ADD_SERVICE: 'ADD_SERVICE',
   DELETE_SERVICE: 'DELETE_SERVICE',
   UPDATE_SERVICE: 'UPDATE_SERVICE',
   GET_ALL_RESERVATIONS: 'GET_ALL_RESERVATIONS',
   DELETE_RESERVATION: 'DELETE_RESERVATION',
   GET_RESERVATION_BY_DATE: 'GET_RESERVATION_BY_DATE',
   LOADING_ADMIN: 'LOADING_ADMIN',
   RESET: 'RESET'
}

export const CLIENT_TYPES = {
   GET_SERVICES: 'GET_SERVICES',
   SERVICE_CATEGORY: 'SERVICE_CATEGORY',
   ADD_CAR: 'ADD_CAR',
   DEL_ITEM_CAR: 'DEL_ITEM_CAR',
   DEL_CAR: 'DEL_CAR',
   GET_CLIENT_RESERVATIONS: 'GET_CLIENT_RESERVATIONS',
   ADD_RESERVATION: 'ADD_RESERVATION',
   LOADING_CLIENT: 'LOADING_CLIENT'
}
