export const AUTH_TYPES = {
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_ERROR: 'LOGIN_ERROR',
   REGISTER_SUCCESS: 'REGISTER_SUCCESS',
   REGISTER_ERROR: 'REGISTER_ERROR',
   SIGNOUT: 'SIGNOUT',
   LOADING: 'LOADING',
   CHECK_ROLE: 'CHECK_ROLE'
}


export const ADMIN_TYPES = {
   GET_ALL_SERVICES: 'GET_ALL_SERVICES',
   ADD_SERVICE: 'ADD_SERVICE',
   DELETE_SERVICE: 'DELETE_SERVICE',
   UPDATE_SERVICE: 'UPDATE_SERVICE',
   GET_ALL_RESERVATIONS: 'GET_ALL_RESERVATIONS',
   GET_RESERVATION_BY_DATE: 'GET_RESERVATION_BY_DATE',
   LOADING: 'LOADING',
   RESET: 'RESET'
}
